### ISSUE TITLE
Homodyne measurement error for large squeezing parameter r

### ISSUE THREAD

**Issue by Hugh-888** [TuringQ/deepquantum#31]
# Problem 
large squeezing parameter r leads to non-positive definite covariance matrix

![image](https://github.com/user-attachments/assets/8186d45d-2940-4f5d-9c98-3005e639bebb)

# code 
```
nmode = 2
circ = dq.QumodeCircuit(nmode=nmode, init_state='vac', cutoff=3, backend='gaussian', basis=True)
circ.s([0], r=11)
st = circ()
circ.draw()
re = circ.measure_homodyne(wires=[0], shots=1)
re 
```

**Comment by sansiro77** [comment]
Maybe we can add an identity matrix of `epsilon=1e-7` or `epsilon=1e-15` to the covariance matrix if the minimum value of its diagonal elements is too small according to the `dtype`.
