### ISSUE TITLE
Non-adjacent BS gate incompatible with batch data encoding

### ISSUE THREAD

**Issue by Hugh-888** [TuringQ/deepquantum#39]
![image](https://github.com/user-attachments/assets/d1baaa4d-0656-492e-b19f-0e3cd0ce6bbf)

**Comment by Hugh-888** [comment]
Using matrix.new_zeros instead
![image](https://github.com/user-attachments/assets/9868c850-0bb6-48bf-bca0-d33bfb40db1d)

**Comment by sansiro77** [comment]
`get_unitary` and `get_displacement` may have similar bugs.
